# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'GithubUserSearchApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubUserSearchApp
  pod 'RxSwift'

  target 'GithubUserSearchAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GithubUserSearchAppUITests' do
    # Pods for testing
  end

end
